name: 'Setup node'
description: 'Setup node and install dependencies from cache'

inputs:
  NPM_AUTH_TOKEN:
    description: 'NPM token'
    required: true
  PROJECT_ROOT:
    default: '.'
    description: 'Base path to npm project'
    required: false
  NODE_VERSION:
    description: 'Node version to use'
    required: true

runs:
  using: "composite"
  steps:
    - name: ⚙️ Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        registry-url: 'https://npm.pkg.github.com'
    - name: ♻️ NPM Cache
      uses: actions/cache@v2
      id: npm-cache
      with:
        path: |
          ${{ inputs.PROJECT_ROOT }}/.npm
          ${{ inputs.PROJECT_ROOT }}/node_modules
          ${{ inputs.PROJECT_ROOT }}/packages/**/node_modules
        key: npm-v3-${{ inputs.PROJECT_ROOT }}-${{ runner.os }}-${{ inputs.NODE_VERSION }}-${{ hashFiles(format('{0}/package-lock.json', inputs.PROJECT_ROOT)) }}
    # Skip post-install scripts here, as a malicious may otherwise steal NPM_AUTH_TOKEN
    - name: 📀 Install
      run: |
        if [[ "${{ steps.npm-cache.outputs.cache-hit }}" == "true" ]]
        then
          echo "Cache hit - skipping dependency installation"
        else
          cd ${{ inputs.PROJECT_ROOT }}
          npm ci --ignore-scripts
          npm run bootstrap -- --ignore-scripts
        fi
      shell: bash
      env:
        CI: "true"
        NODE_AUTH_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}
