name: 'Setup node'
description: 'Setup node and install dependencies from cache'

inputs:
  COMMAND:
    default: 'npm ci --ignore-scripts'
    description: 'Install command to run'
    required: false
  NPM_AUTH_TOKEN:
    description: 'NPM token'
    required: true
  NODE_VERSION:
    description: 'Node version to use'
    required: true
  PROJECT_ROOT:
    default: '.'
    description: 'Base path to npm project'
    required: false
  CACHE_CHILD_NODE_MODULES:
    default: "false"
    description: 'When true all <PROJECT_ROOT>/**/node_modules is added to the cache'
    required: false

runs:
  using: "composite"
  steps:
    - name: ⚙️ Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        registry-url: 'https://npm.pkg.github.com'
    - name: ♻️ NPM Cache
      uses: actions/cache@v2
      id: npm-cache
      with:
        path: |
          ${{ inputs.PROJECT_ROOT }}/.npm
          ${{ inputs.PROJECT_ROOT }}/node_modules
          ${{ inputs.CACHE_CHILD_NODE_MODULES == "true" && format('{0}/**/node_modules', inputs.PROJECT_ROOT) || '' }}
        key: npm-v3-${{ runner.os }}-${{ inputs.NODE_VERSION }}-${{ hashFiles(format('{0}/package-lock.json', inputs.PROJECT_ROOT)) }}
    # Skip post-install scripts here, as a malicious may otherwise steal NPM_AUTH_TOKEN
    - name: 📀 Install
      run: |
        if [[ "${{ steps.npm-cache.outputs.cache-hit }}" == "true" ]]
        then
          echo "Cache hit - skipping dependency installation"
        else
          echo "No chache hit - installing with command: ${{ inputs.COMMAND }}"
          cd ${{ inputs.PROJECT_ROOT }}
          ${{ inputs.COMMAND }}
        fi
      shell: bash
      env:
        CI: "true"
        NODE_AUTH_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}
