name: 'Restore cache'
description: 'Restore cache or fail.'

inputs:
  KEY:
    description: 'Key of the cache to restore.'
    required: true
  PATH:
    description: 'Paths of the cache to restore.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore cache
      uses: actions/cache@v2
      id: restore
      with:
        path: ${{ inputs.PATH }}
        key: ${{ inputs.KEY }}
    - name: Verify
      id: result
      run: |
        if [[ "${{ steps.restore.outputs.cache-hit }}" == "true" ]]
        then
          echo "Cache restored!"
        else
          echo "Cache not found!"
          exit 1
        fi
      shell: bash

