name: "⬇️ Install lokalise2 CLI"
description: "Install lokalise CLI and add it to path"

runs:
  using: "composite"
  steps:
    - name: ⬇️ Install lokalise2 CLI
      run: |
        curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
